### ISSUE TITLE
Signal handling GC / cleanup running on PHP 7.1

### ISSUE THREAD

**Issue by martinschroeder** [bwoebi/php-uv#25]
There seems to be a problem (maybe memory leak?) related to uv signal handling when running the async interop loop test case with libuv using PHP 7.1. You can observe this behavior in the [travis builds of a loop implementation](https://travis-ci.org/koolkode/async). The test case testNoMemoryLeak always fails when 'onSignal' is being used. The same test case succeeds running on PHP 7.0.

**Comment by bwoebi** [comment]
I think your code is bogus there. You end up not stopping a lot of signal watchers.

You just stop the signal watcher when there's only one left in https://github.com/koolkode/async/blob/master/src/Loop/UvLoop.php#L637
but not all the others.

Also https://github.com/koolkode/async/blob/master/src/Loop/UvLoop.php#L472 looks like dead code - signalEvents is never being assigned to, so the isset will always be false.

Also note that with 7.0 it should fail too, but you have coverage active, so that test is skipped (you cannot test memory related issues with coverage active as coverage consumes itself quite some the memory).

**Comment by martinschroeder** [comment]
Good catch. There was an assignment to signal events missing...
Sorry to have bothered you with that. I need to test this implementation a lot more.

Thanks for your help.
