### ISSUE TITLE
uv_spawn example discrepancy

### ISSUE THREAD

**Issue by CharlotteDunois** [bwoebi/php-uv#75]
I'm trying to get `uv_spawn` to work, since it pretty much does not work as expected (no output whatsoever on Windows, always EOF immediately), I tried to use the `spawn` example (`examples/spawn_fd.php`, but with `uv_read_start`) and it leads on two platforms to two different results.

Test script (I've added an assert in the read callback): 
```php
$in  = uv_pipe_init(uv_default_loop(), true);
$out = uv_pipe_init(uv_default_loop(), true);

echo "HELLO ";

$stdio = array();
$stdio[] = uv_stdio_new($in, UV::CREATE_PIPE | UV::READABLE_PIPE);
$stdio[] = uv_stdio_new($out, UV::CREATE_PIPE | UV::WRITABLE_PIPE);

$flags = 0;
uv_spawn(uv_default_loop(), "php", array('-r','var_dump($_ENV);'), $stdio, __DIR__,
         array("KEY"=>"hello"),
    function($process, $stat, $signal){
        uv_close($process,function(){});

    }, $flags);

uv_read_start($out, function($out, $nread, $buffer){
assert($nread >= 0);
    echo $buffer;

    uv_close($out,function(){});
});

uv_run();
```

Debian Jessie PHP 7.3.3 NTS with libuv 1.9.1 and php-uv 0.2.4 compiled through PECL:
```
HELLO 
array(0) {
}
```
Assertion does not fail, however the environment is empty in the child PHP process. Exit callback gets called with exit code `0` and term sig `0`.

Windows 7 x64 (and Windows 10 x64 1803) with php-uv 0.2.4 (and libuv) compiled through PECL:
```
HELLO 
PHP Warning:  assert(): assert($nread >= 0) failed in test2.php on line 32
```
Assertion fails due to `$nread === -4095` (EOF). Exit callback gets called with exit code `0` and term sig `0`.

Even if I add `UV_OVERLAPPED_PIPE` (`0x40`) on Windows, it does not change anything.

Do you have a clue what is going wrong (at least for the debian one)?

**Comment by bwoebi** [comment]
Regarding the $_ENV issue - not sure what exactly causes $_ENV to misbehave. using getenv() works. Using my own compiled master version of PHP worked as well. Using the pre-installed php 7.3 from distro did not...

Regarding windows, I currently have no idea. Possibly it is an upstream bug? I see nothing real going wrong, also from what I see, the code we are executing is pretty much similar to https://github.com/libuv/libuv/blob/a74e54bc8fab57c02eabda907e7b5d10451d0a99/test/test-spawn.c#L254 (after all, it works on linux...)

**Comment by CharlotteDunois** [comment]
The Node.js CI seems to pass in that regard <https://ci.nodejs.org/job/libuv-test-commit-windows-cmake/lastCompletedBuild/console>.

However I noticed that the given environment variable is truncated. When inspecting the process in Process Monitor (from Sysinternals), the `KEY=hell` appears (missing `o`).

But it seems there is a bigger problem, I only receive partial output (I don't get an immediate EOF) for spawning a `cmd.exe` process. However the output is gone again once I run `cmd.exe /c "php.exe -r "var_dump($argv, $_ENV);""` through php-uv, although that is perfectly valid...

**Comment by bwoebi** [comment]
The missing o is indeed a bug. I will fix that one.

No idea about windows (I actually never had to debug C code on windows … would have to look into how that works there at all).

**Comment by DaveRandom** [comment]
The `$_ENV` issue seems likely to be related to the `variables_order` ini setting. Without an ini file the default behaviour `EGPCS` will populate the superglobal, however the default value `GPCS` in the packaged ini file(s) does not. I'm guessing Bob's master build was run without an ini file, hence the difference in behaviour. `getenv()` should always work regardless of this setting.

---

re Windoze and `CreateProcess()` apparently misbehaving, here are the things I would test, in roughly this order...

- Does `php -v` produce any output?
- Does it make any difference if you have the child execute a script file, rather than using `-r` and passing code on the command line?
- How about any other standalone binary console executable (i.e. not cmd.exe, not a batch file and not a shell built-in such as `dir`)? `ipconfig` is a good test case, it's available everywhere and highly unlikely to fall foul of any kind of permissions issue. For testing a longer running child which continuously produces output, `ping 127.0.0.1` is a pretty simple/safe bet.
- I notice the sample code does not do anything with stderr. It's unlikely since the exit code is reported as `0`, but it's worth inspecting in case there are any clues there. Equally, do you get a different result if you pass `['-ddisplay_errors=1', '-derror_reporting=-1', '-r', 'var_dump($_ENV);']`?
- If you `var_dump($buffer)` before the assertion, what does it contain? Is it possible that `$nread` is erroneously reporting an EOF that was encountered after a successful read in which the buffer has been hydrated?
- Escaping args on Windows is hard. I can't see any obvious bugs from a cursory glance at libuv, but can you check whether passing the `UV::PROCESS_WINDOWS_VERBATIM_ARGUMENTS` flag makes any difference? (This should completely bypass the escape routine in libuv)
- [This commit](https://github.com/libuv/libuv/commit/1fc72276f91c7d378f14dfd0bb6b0ca8667e4bc5) relates to spawn/env on Windows. I don't think it's applicable here, but worth ruling out.

My gut feeling is that this is in some way related to the way data is formatted and passed to the child process, rather than an issue with the actual creation/behaviour of the child. I suspect that the reason you got EOF is because it really was the end of the pipe, and the child process didn't produce any output on stdout.

I would advise against tests involving cmd.exe as this has it's own extra layer of weirdness around data interpretation and can only add to the confusion. Even if your end goal is to bounce your command through cmd to give access to shell features, try get direct invocations working reliably first.

I don't have a sane dev environment to try and repro this with a debugger right now, however I will try and take a look on my work machine when I have time. Can you confirm the PHP version/VC version/architecture/ZTS mode of the Windows build(s) you have been testing with?

**Comment by CharlotteDunois** [comment]
Thanks for your comment, I've added my answers to any questions!

> The `$_ENV` issue seems likely to be related to the `variables_order` ini setting. Without an ini file the default behaviour `EGPCS` will populate the superglobal, however the default value `GPCS` in the packaged ini file(s) does not. I'm guessing Bob's master build was run without an ini file, hence the difference in behaviour. `getenv()` should always work regardless of this setting.

That was it, it works on Debian now.

>     * Does `php -v` produce any output?

Yes, although partial. The first line is missing.

>     * Does it make any difference if you have the child execute a script file, rather than using `-r` and passing code on the command line?

No.

>     * How about any other standalone binary console executable (i.e. not cmd.exe, not a batch file and not a shell built-in such as `dir`)? `ipconfig` is a good test case, it's available everywhere and highly unlikely to fall foul of any kind of permissions issue. For testing a longer running child which continuously produces output, `ping 127.0.0.1` is a pretty simple/safe bet.

Same as `php -v`, partial output (some parts of the beginning is missing).

>     * I notice the sample code does not do anything with stderr. It's unlikely since the exit code is reported as `0`, but it's worth inspecting in case there are any clues there. Equally, do you get a different result if you pass `['-ddisplay_errors=1', '-derror_reporting=-1', '-r', 'var_dump($_ENV);']`?

I am handling `stderr` in my local script, same as stdout - instant EOF. No difference in result.

>     * If you `var_dump($buffer)` before the assertion, what does it contain? Is it possible that `$nread` is erroneously reporting an EOF that was encountered after a successful read in which the buffer has been hydrated?

`$buffer` is `null` on EOF.

>     * Escaping args on Windows is hard. I can't see any obvious bugs from a cursory glance at libuv, but can you check whether passing the `UV::PROCESS_WINDOWS_VERBATIM_ARGUMENTS` flag makes any difference? (This should completely bypass the escape routine in libuv)

Does not make any difference, I've already played with that.

> My gut feeling is that this is in some way related to the way data is formatted and passed to the child process, rather than an issue with the actual creation/behaviour of the child. I suspect that the reason you got EOF is because it really was the end of the pipe, and the child process didn't produce any output on stdout.
> 
> I would advise against tests involving cmd.exe as this has it's own extra layer of weirdness around data interpretation and can only add to the confusion. Even if your end goal is to bounce your command through cmd to give access to shell features, try get direct invocations working reliably first.

I did first try to test without cmd, but missing success made me try with a shell to see if it makes a difference.

> I don't have a sane dev environment to try and repro this with a debugger right now, however I will try and take a look on my work machine when I have time. Can you confirm the PHP version/VC version/architecture/ZTS mode of the Windows build(s) you have been testing with?
PHP 7.2.17 MSVC15 x64 ZTS. I'lll try a clean build with only libuv and the bundled extensions sometime later.

**Comment by CharlotteDunois** [comment]
I've tried now with a clean PHP build with only php-uv and the bundled extensions.
```
PHP 7.4.0 (cli) (built: Nov 27 2019 10:14:18) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
```

And I still only get partial output. When I try to spawn a `php -v` process, I only get:
```
(built: Nov 27 2019 10:14:18) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
```

**Comment by techno-express** [comment]
The documentation/usage for function `uv_pipe_init` is wrong.
The example:
>$in  = uv_pipe_init(uv_default_loop(), true);
$out = uv_pipe_init(uv_default_loop(), true);

Needs to be:
>$in  = uv_pipe_init(uv_default_loop(), false);
$out = uv_pipe_init(uv_default_loop(), false);

I was having the same issue on **Windows 7 64bit, PHP 7.2 zts,**
until making the changes, now works as expected.

**Comment by CharlotteDunois** [comment]
@techno-express I don't know why it is wrong. The libuv documentation describes the second argument as whether the pipe will be used for passing handles between processes. Maybe Windows just isn't supported with the `ipc` argument as `true`. But then we'd need to take this to libuv. I've looked through the tests and the Node.js libuv CI build, this functionality doesn't seem to be tested on Windows...
